// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: internal/proto/job_worker_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Job struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Job) Reset() {
	*x = Job{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_job_worker_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_job_worker_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_internal_proto_job_worker_service_proto_rawDescGZIP(), []int{0}
}

func (x *Job) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type JobStartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cpu              float64  `protobuf:"fixed64,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	MemBytes         int64    `protobuf:"varint,2,opt,name=mem_bytes,json=memBytes,proto3" json:"mem_bytes,omitempty"`
	IoBytesPerSecond int64    `protobuf:"varint,3,opt,name=io_bytes_per_second,json=ioBytesPerSecond,proto3" json:"io_bytes_per_second,omitempty"`
	Command          string   `protobuf:"bytes,4,opt,name=command,proto3" json:"command,omitempty"`
	Args             []string `protobuf:"bytes,5,rep,name=args,proto3" json:"args,omitempty"`
}

func (x *JobStartRequest) Reset() {
	*x = JobStartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_job_worker_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStartRequest) ProtoMessage() {}

func (x *JobStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_job_worker_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStartRequest.ProtoReflect.Descriptor instead.
func (*JobStartRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_job_worker_service_proto_rawDescGZIP(), []int{1}
}

func (x *JobStartRequest) GetCpu() float64 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *JobStartRequest) GetMemBytes() int64 {
	if x != nil {
		return x.MemBytes
	}
	return 0
}

func (x *JobStartRequest) GetIoBytesPerSecond() int64 {
	if x != nil {
		return x.IoBytesPerSecond
	}
	return 0
}

func (x *JobStartRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *JobStartRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

type JobStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status     string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ExitCode   int32  `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	ExitReason string `protobuf:"bytes,3,opt,name=exit_reason,json=exitReason,proto3" json:"exit_reason,omitempty"`
}

func (x *JobStatus) Reset() {
	*x = JobStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_job_worker_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStatus) ProtoMessage() {}

func (x *JobStatus) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_job_worker_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStatus.ProtoReflect.Descriptor instead.
func (*JobStatus) Descriptor() ([]byte, []int) {
	return file_internal_proto_job_worker_service_proto_rawDescGZIP(), []int{2}
}

func (x *JobStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *JobStatus) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *JobStatus) GetExitReason() string {
	if x != nil {
		return x.ExitReason
	}
	return ""
}

type Output struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content []byte `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *Output) Reset() {
	*x = Output{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_job_worker_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Output) ProtoMessage() {}

func (x *Output) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_job_worker_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Output.ProtoReflect.Descriptor instead.
func (*Output) Descriptor() ([]byte, []int) {
	return file_internal_proto_job_worker_service_proto_rawDescGZIP(), []int{3}
}

func (x *Output) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type JobStopResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *JobStopResponse) Reset() {
	*x = JobStopResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_job_worker_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobStopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStopResponse) ProtoMessage() {}

func (x *JobStopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_job_worker_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStopResponse.ProtoReflect.Descriptor instead.
func (*JobStopResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_job_worker_service_proto_rawDescGZIP(), []int{4}
}

var File_internal_proto_job_worker_service_proto protoreflect.FileDescriptor

var file_internal_proto_job_worker_service_proto_rawDesc = []byte{
	0x0a, 0x27, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x6a, 0x6f, 0x62, 0x5f, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x6a, 0x6f, 0x62, 0x77, 0x6f,
	0x72, 0x6b, 0x65, 0x72, 0x22, 0x15, 0x0a, 0x03, 0x4a, 0x6f, 0x62, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x9d, 0x01, 0x0a, 0x0f,
	0x4a, 0x6f, 0x62, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x63, 0x70, 0x75, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x63, 0x70,
	0x75, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x65, 0x6d, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x6d, 0x65, 0x6d, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x2d,
	0x0a, 0x13, 0x69, 0x6f, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x5f, 0x70, 0x65, 0x72, 0x5f, 0x73,
	0x65, 0x63, 0x6f, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x10, 0x69, 0x6f, 0x42,
	0x79, 0x74, 0x65, 0x73, 0x50, 0x65, 0x72, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18,
	0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x22, 0x61, 0x0a, 0x09, 0x4a,
	0x6f, 0x62, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x1b, 0x0a, 0x09, 0x65, 0x78, 0x69, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x65, 0x78, 0x69, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1f, 0x0a,
	0x0b, 0x65, 0x78, 0x69, 0x74, 0x5f, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x65, 0x78, 0x69, 0x74, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x22,
	0x0a, 0x06, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x22, 0x11, 0x0a, 0x0f, 0x4a, 0x6f, 0x62, 0x53, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xda, 0x01, 0x0a, 0x09, 0x4a, 0x6f, 0x62, 0x57, 0x6f, 0x72,
	0x6b, 0x65, 0x72, 0x12, 0x35, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x1a, 0x2e, 0x6a,
	0x6f, 0x62, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2e, 0x4a, 0x6f, 0x62, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x6a, 0x6f, 0x62, 0x77, 0x6f,
	0x72, 0x6b, 0x65, 0x72, 0x2e, 0x4a, 0x6f, 0x62, 0x22, 0x00, 0x12, 0x2f, 0x0a, 0x05, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x12, 0x0e, 0x2e, 0x6a, 0x6f, 0x62, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2e,
	0x4a, 0x6f, 0x62, 0x1a, 0x14, 0x2e, 0x6a, 0x6f, 0x62, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2e,
	0x4a, 0x6f, 0x62, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x00, 0x12, 0x2f, 0x0a, 0x06, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x0e, 0x2e, 0x6a, 0x6f, 0x62, 0x77, 0x6f, 0x72, 0x6b, 0x65,
	0x72, 0x2e, 0x4a, 0x6f, 0x62, 0x1a, 0x11, 0x2e, 0x6a, 0x6f, 0x62, 0x77, 0x6f, 0x72, 0x6b, 0x65,
	0x72, 0x2e, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22, 0x00, 0x30, 0x01, 0x12, 0x34, 0x0a, 0x04,
	0x53, 0x74, 0x6f, 0x70, 0x12, 0x0e, 0x2e, 0x6a, 0x6f, 0x62, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72,
	0x2e, 0x4a, 0x6f, 0x62, 0x1a, 0x1a, 0x2e, 0x6a, 0x6f, 0x62, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72,
	0x2e, 0x4a, 0x6f, 0x62, 0x53, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x42, 0x5a, 0x40, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x64, 0x75, 0x73, 0x74, 0x69, 0x6e, 0x73, 0x70, 0x65, 0x63, 0x6b, 0x65, 0x72, 0x2f, 0x6c,
	0x69, 0x6e, 0x75, 0x78, 0x2d, 0x6a, 0x6f, 0x62, 0x2d, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2d,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_proto_job_worker_service_proto_rawDescOnce sync.Once
	file_internal_proto_job_worker_service_proto_rawDescData = file_internal_proto_job_worker_service_proto_rawDesc
)

func file_internal_proto_job_worker_service_proto_rawDescGZIP() []byte {
	file_internal_proto_job_worker_service_proto_rawDescOnce.Do(func() {
		file_internal_proto_job_worker_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_proto_job_worker_service_proto_rawDescData)
	})
	return file_internal_proto_job_worker_service_proto_rawDescData
}

var file_internal_proto_job_worker_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_proto_job_worker_service_proto_goTypes = []any{
	(*Job)(nil),             // 0: jobworker.Job
	(*JobStartRequest)(nil), // 1: jobworker.JobStartRequest
	(*JobStatus)(nil),       // 2: jobworker.JobStatus
	(*Output)(nil),          // 3: jobworker.Output
	(*JobStopResponse)(nil), // 4: jobworker.JobStopResponse
}
var file_internal_proto_job_worker_service_proto_depIdxs = []int32{
	1, // 0: jobworker.JobWorker.Start:input_type -> jobworker.JobStartRequest
	0, // 1: jobworker.JobWorker.Query:input_type -> jobworker.Job
	0, // 2: jobworker.JobWorker.Stream:input_type -> jobworker.Job
	0, // 3: jobworker.JobWorker.Stop:input_type -> jobworker.Job
	0, // 4: jobworker.JobWorker.Start:output_type -> jobworker.Job
	2, // 5: jobworker.JobWorker.Query:output_type -> jobworker.JobStatus
	3, // 6: jobworker.JobWorker.Stream:output_type -> jobworker.Output
	4, // 7: jobworker.JobWorker.Stop:output_type -> jobworker.JobStopResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_proto_job_worker_service_proto_init() }
func file_internal_proto_job_worker_service_proto_init() {
	if File_internal_proto_job_worker_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_proto_job_worker_service_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Job); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_job_worker_service_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*JobStartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_job_worker_service_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*JobStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_job_worker_service_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*Output); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_job_worker_service_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*JobStopResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_proto_job_worker_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_job_worker_service_proto_goTypes,
		DependencyIndexes: file_internal_proto_job_worker_service_proto_depIdxs,
		MessageInfos:      file_internal_proto_job_worker_service_proto_msgTypes,
	}.Build()
	File_internal_proto_job_worker_service_proto = out.File
	file_internal_proto_job_worker_service_proto_rawDesc = nil
	file_internal_proto_job_worker_service_proto_goTypes = nil
	file_internal_proto_job_worker_service_proto_depIdxs = nil
}
